apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: wordpress-app
type: Opaque
stringData: 
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_DATABASE: "${MYSQL_DATABASE}"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflare # Note: This must match the cloudflared deployment namespace
type: Opaque
stringData: 
  token: "${CLOUDFLARE_TUNNEL_TOKEN}"